checkgame/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('game_app.urls')),
    path('check237/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game_app/urls.py
from django.urls import path
from .views import home, handle_requests,play_request,game_session,get_cardings,pick

app_name = 'game_app'
urlpatterns = [
    path('', home, name="home"),
    path('handle/', handle_requests, name="handle_requests"),
    path('play/', game_session, name="game_session"),
    path('send_request/', play_request, name="play_request"),
    path('get_cardlist/', get_cardings, name="get_cardings"),
    path('pick/', pick, name="pick")
    
]

game_app/models.py
from django.db import models
from django.conf import settings
from django.contrib.postgres.fields import ArrayField
from django.shortcuts import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from datetime import datetime, timedelta
import random
from django.db.models import JSONField
from django.urls import reverse,resolve


def get_deck():
    deck = ["AH", "AC", "AD", "AS", "2H", "2C", "2D", "2S", "3H", "3C", "3D", "3S", "4H", "4C", "4D", "4S", "5H", "5C",
            "5D", "5S",
            "6H", "6C", "6D", "6S", "7H", "7C", "7D", "7S", "8H", "8C", "8D", "8S", "9H", "9C", "9D", "9S", "10H",
            "10C",
            "10D", "10S",
            "JH", "JC", "JD", "JS", "QH", "QC", "QD", "QS", "KH", "KC", "KD", "KS", "RL", "BL"]
    return deck


class CheckGameSession(models.Model):
    name = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.name
    
    def reset(self):
        player1 = self.player_set.get(div = 'player-1')
        player2 = self.player_set.get(div = 'player-2')
        playboard = self.playboard_set.all()[0]
        dealboard = self.dealboard_set.all()[0]
        player1.initialize()
        player2.initialize()
        playboard.initialize()
        dealboard.initialize()
        dealboard.deal_to_player(player1,5)
        dealboard.deal_to_player(player2,5)
        player2.hasPlayed = True
        player2.save()
        player1.hasPlayed = False
        player1.hasPicked = False
        player1.save()
        dealboard.deal_to_playboard(playboard,1)
        self.save()
         
         
class Player(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    cards = ArrayField(ArrayField(models.CharField(max_length=3)), default=list)
    hasPlayed = models.BooleanField(default=False)
    hasPicked = models.BooleanField(default=False)
    div = models.CharField(max_length=30, null=True)
    game_session = models.ForeignKey(CheckGameSession, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.user.username
    
    def initialize(self):
        self.cards = []
        self.save()
     

class PlayBoard(models.Model):
    name = models.CharField(max_length=30, default='playboard')
    card_dict = JSONField(default=list)
    div = models.CharField(max_length=30, default='#board')
    game_session = models.ForeignKey(CheckGameSession, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name
    
    def initialize(self):
        self.card_dict = []
        self.save()


class DealBoard(models.Model):
    name = models.CharField(max_length=30, default='dealboard')
    cards = ArrayField(ArrayField(models.CharField(max_length=3)), default=get_deck)
    div = models.CharField(max_length=30, default='dealboard-deck')
    game_session = models.ForeignKey(CheckGameSession, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name
    
    def deal_to_player(self,player, num):
        if num <= len(self.cards) and len(self.cards) != 0:
            for i in range(0,num):
                cardy = self.random_card()
                player.cards.append(cardy)
                player.save()
                self.remove(cardy)
                self.save()
        else:
            j = len(self.cards)
            k = num - len(self.cards)
            if j != 0:
                self.deal_to_player(player,j)
            game_session = self.game_session
            playboard = game_session.playboard_set.all()[0]
            n = len(playboard.card_dict)-2
            for i in range(0,n):
                if playboard.card_dict[i]["played_by"] != 'command':
                    self.cards.append(playboard.card_dict[i]["card"])
            self.save()
            playboard.card_dict = playboard.card_dict[n:]
            playboard.save()
            self.deal_to_player(player, k)
            
    def deal_to_playboard(self,playboard, num):
        for i in range(0,num):
            cardy = self.random_card()
            while cardy in ["AH", "AC", "AD", "AS", "7H", "7C", "7D", "7S", "RL", "BL"]:
                cardy = self.random_card()
            playboard.card_dict.append({'card':cardy,'played_by':'dealboard'})
            playboard.save()
            self.remove(cardy)
            self.save()
    
    def random_card(self):
        random_index = random.randint(0, len(self.cards)-1)
        card = self.cards[random_index]
        return card
    
    def remove(self, card):
        temp = []
        for item in self.cards:
            if item not in card:
                temp.append(item)
        self.cards = temp
        self.save()     
        
    def initialize(self):
        self.cards = []
        self.cards = get_deck()
        self.save()

class Requests(models.Model):
    created = models.TimeField(auto_now_add=True)
    send_to = models.CharField(max_length=30)
    recieved_from = models.CharField(max_length=30)
    is_replied = models.BooleanField(default=False)
    is_rejected = models.BooleanField(default=False)
    
    class Meta:
        verbose_name = 'Requests'
        verbose_name_plural = 'Requests'
    
    def recent(self):
        return self.created >= timezone.now() - datetime.timedelta(minutes=2)
    
    def __str__(self):
        return 'from ' + self.recieved_from + ' to ' + self.send_to
    

 
    

game_app/forms.py
from django import forms

CHOICES = [('1', 'YES')]


class Choice(forms.Form):
    choice = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)

game_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.sessions.models import Session
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .models import Player, DealBoard, PlayBoard, CheckGameSession, Requests
from .forms import Choice
from django.http import JsonResponse
import json
from django.core import serializers
from django.urls import reverse,resolve
from django.contrib import messages


# function to get the users that are currently login to the website
def get_current_users():
    active_sessions = Session.objects.filter(expire_date__gte=timezone.now())
    user_id_list = []
    for session in active_sessions:
        data = session.get_decoded() 
        user_id_list.append(data.get('_auth_user_id', None))
    # Query all logged in users based on id list
    return User.objects.filter(id__in=user_id_list)

# the home display view
def home(request):
    online_users = get_current_users()
    recieved = Requests.objects.filter(recieved_from = request.user.username)
    if recieved:
        for item in recieved:
            if item.is_rejected:
                item.delete()
                
    game_session = CheckGameSession.objects.filter(name__icontains = request.user.username)
    if game_session:
        messages.info(request, 'You are in a game session')
    context = {
        'users': online_users
    }
    return render(request, 'game_app/home.html', context)


# function to send play request
@login_required
def play_request(request):
    if request.POST and request.POST.get('selected_user') is not None:
        request_to = request.POST.get('selected_user')
        request_from = request.user.username
        game_sessions = CheckGameSession.objects.filter(name__icontains = request_to)
        if game_sessions:
            messages.info(request, request_to + ' is already in a game session')
            return redirect('/')
        else:
            Requests.objects.create(send_to = request_to, recieved_from = request_from)
            return render(request, 'game_app/waiting.html')
        
    request_list = json.loads(serializers.serialize('json',Requests.objects.all()))
    
    return JsonResponse(request_list, safe=False)
        
   
       

# creating the game session 
@login_required
def handle_requests(request):
    #saving the request reply
    if request.POST.get('option')[:3] == 'yes' :
        recieved_from = request.POST.get('option')[4:]
        requested = Requests.objects.filter(recieved_from = recieved_from, send_to = request.user.username)
        for item in requested:
            item.is_replied = True
            item.save()
        
        games = CheckGameSession.objects.filter(name__icontains = request.user.username)
        if games:
            return redirect('/')
        else:
            #getting the players
            player1_user = request.user
            player1 = player1_user.username
            player2 = request.POST.get('option')[4:]
            player2_user = User.objects.get(username=player2)
            
            #creating the game session
            gaming_session = CheckGameSession.objects.create()
            gameplayer1 = Player.objects.create(user=player1_user, div="player-1", game_session=gaming_session)
            gameplayer2 = Player.objects.create(user=player2_user, div="player-2", hasPlayed = True, game_session=gaming_session)
        
            # naming the game session
            gaming_session.name = player1 + ' ' + str(gaming_session.pk) + ' ' + player2
            gaming_session.save()
            # creating the playboard and dealboard
            playboard = PlayBoard.objects.create(name=str(gaming_session.pk) + ' playboard',
                                                game_session=gaming_session)
            dealboard = DealBoard.objects.create(name=str(gaming_session.pk)  + ' dealboard',
                                                game_session=gaming_session)
            
            #setting initials
            dealboard.deal_to_player(gameplayer1,5)
            dealboard.deal_to_player(gameplayer2,5)
            dealboard.deal_to_playboard(playboard,1)
            
            return render(request, 'game_app/creating.html')
    
    if request.POST.get('option')[:2] == 'no':
        recieved_from = request.POST.get('option')[3:]
        requested = Requests.objects.filter(recieved_from = recieved_from, send_to = request.user.username)
        for item in requested:
            item.is_replied = True
            item.is_rejected = True
            item.save()
        return redirect('/')
    
    return redirect('/')

#the main game session view  where the game is played
@login_required
def game_session(request):
    user = request.user
    if Player.objects.filter(user=user):
        player = Player.objects.get(user=user)
        gaming_session = player.game_session
        player1 = gaming_session.player_set.get(div='player-1')
        player2 =  gaming_session.player_set.get(div='player-2')
        recieved = Requests.objects.filter(recieved_from = player.user.username)
        if recieved:
            for item in recieved:
                if item.is_replied:
                    item.delete()
        playboard = PlayBoard.objects.get(game_session = gaming_session)
        dealboard = DealBoard.objects.get(game_session = gaming_session)
        
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            card = json.load(request)['card']
            if card in player.cards:
                player.cards.remove(card)
                player.hasPicked = False
                player.save()
                playboard.card_dict.append({'card':card,'played_by':player.div})
                playboard.save()
                player1 = gaming_session.player_set.get(div='player-1')
                player2 =  gaming_session.player_set.get(div='player-2')
                if '7' in card:
                    if player == player1:
                        dealboard.deal_to_player(player2,2)
                        player2.save()
                    if player == player2:
                        dealboard.deal_to_player(player1,2)
                        player1.save()
                if 'L' in card:
                    if player == player1:
                        dealboard.deal_to_player(player2,4)
                        player2.save()
                    if player == player2:
                        dealboard.deal_to_player(player1,4)
                        player1.save()
                make_play_change(player,player1,player2)
            if card == 'R':
                gaming_session.reset()
            if card in ['H','C','D','S']:
                playboard.card_dict.append({'card':card,'played_by':'command'})
                playboard.save()
            if (len(player.cards) == 0) and (card != 'R') and (not card in ['H','C','D','S']):
                player.score = player.score + 1
                player.save()
            data = {
                'user_cards': player.cards,
                'playboard_cards': playboard.card_dict,
                'hasPlayed':player.hasPlayed,
                'hasPicked':player.hasPicked,
                'score':player.score
            }
            return JsonResponse(data)
        
    else:
        return redirect('/')
    
    
     # handling the leave session form
    if request.method == 'POST':
        form = Choice(request.POST)
        if form.is_valid():
            if form.cleaned_data['choice'] == '1':
                player = Player.objects.get(user=user)
                delete_game = player.game_session
                delete_game.delete()
            return redirect('/')
    else:
        form = Choice()

    context = {
        'player1': player1,
        'player2': player2,
        'playboard': playboard,
        'dealboard':dealboard,
        'form': form
    }
    return render(request, 'game_app/play.html', context)


#get the list of card of the check game objects
@login_required
def get_cardings(request):
    user = request.user
    player = Player.objects.get(user=user)
    gaming_session = player.game_session
    playboard = PlayBoard.objects.get(game_session = gaming_session)
    dealboard = DealBoard.objects.get(game_session = gaming_session)
    player1 = gaming_session.player_set.get(div='player-1')
    player2 =  gaming_session.player_set.get(div='player-2')
    if player == player1:
        other_player = player2
    if player == player2:
        other_player = player1
    data = {
        'cards1':player.cards,
        'cards2':playboard.card_dict,
        'cards3':dealboard.cards,
        'divi':player.div,
        'hasPlayed':player.hasPlayed,
        'hasPicked':player.hasPicked,
        'score':player.score,
        'name':player.user.username,
        'otherPlayer_hasPicked':other_player.hasPicked,
        'otherPlayer_hasPlayed':other_player.hasPlayed,
        'otherPlayer_numcards':len(other_player.cards),
        'otherPlayer_score':other_player.score
        }
        
    return JsonResponse(data)
        
#pick a card by the player
@login_required
def pick(request):
    user = request.user
    player = Player.objects.get(user=user)
    game = player.game_session
    dealboard = DealBoard.objects.get(game_session=game)
    dealboard.deal_to_player(player,1)
    player.hasPicked = True
    player.save()
    player1 = game.player_set.get(div='player-1')
    player2 =  game.player_set.get(div='player-2')
    make_play_change(player,player1,player2)
    data = {
        'cards1':player.cards,
        'cards3':dealboard.cards,
        'divi':player.div,
        'hasPlayed':player.hasPlayed,
        'hasPicked':player.hasPicked
        }
        
    return JsonResponse(data)

def make_play_change(player,player1,player2):
    if player == player1:
        player1.hasPlayed = True
        player1.save()

game_app/templates/game_app/base.html
{%  load static %}
{% load socialaccount %}
{% providers_media_js %} 
<html>
    <head>
        <title> Check </title>
        <link rel="icon" href="{% static 'game_app/images/heart.png' %}" type="image/png">
         <link rel="stylesheet" href="{% static 'game_app/css/bootstrap.css' %}">
         <link rel="stylesheet" href="{% static 'game_app/css/style.css' %}">
         <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body>
        <div class="bg">
       <div class="container-fluid">
           <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand" href="{% url 'game_app:home' %}">
                        <img class="logo" src="{% static 'game_app/images/logo.jpg' %}" width="30" height="30" class="d-inline-block align-top" alt="CardCheck">
                        CardCheck
                      </a>
                      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'game_app:home' %}"> Home </a><span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Option
                            </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="#">Game setting</a>
                            <a class="dropdown-item" href="#">Theme</a>
                        </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"> Help </a>
                        </li>
                    </ul>
                    <span class="navbar-text ">
                        {% if user.is_authenticated %}
                        Signed in as <span id="username">{{user.username}}</span>/
                        <a href="{% url 'account_logout' %}">SignOut</a>
                        {% else %}
                        <a href='{% provider_login_url "facebook" method="oauth2" %}' class="fb btn mr-2">
                            <i class="fa fa-facebook fa-fw"></i> Login with Facebook
                        </a>
                        <a class="btn signin mr-2" href="{% url 'account_login' %}">SignIn
                        </a>
                        {% endif %}
                    </span>
                </div>
           </nav>
       </div>

       {% block body %}

    <div class="p-3 col-6 offset-3">
          {% block content %}
    {% endblock %}
    </div>
    {% endblock %}
</div>
    <script src="{% static 'game_app/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'game_app/js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'game_app/js/bootstrap.js' %}"></script>
</body>
</html>

game_app/templates/game_app/creating.html
{% extends "game_app/base.html" %}
{% load static %}
{% block body %}
<html>
<head>
    <title>

    </title>
    <link rel="stylesheet" href="{% static 'game_app/css/style.css' %}">
</head>
<body>
<h1 class="mt-3" style="text-align:center">The game has been created tap Play</h1>
<div class="d-flex justify-content-center">
    <form action="{% url 'game_app:game_session' %}" method="get">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Play</button>
    </form>    
</div>
<script src="{% static 'game_app/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'game_app/js/requests.js' %}"></script>
</body>
</html>
{% endblock %}

game_app/templates/game_app/home.html
{% extends "game_app/base.html" %}
{% load static %}
{% block body %}
<html>
<head>
    <title>

    </title>
    <link rel="stylesheet" href="{% static 'game_app/css/style.css' %}">
</head>
<body>
    {% if messages %}
        {%for message in messages%}
        <div class="alert alert-info alert-dismissible" role="alert">
            <span type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></span>
            <strong>{{message}}</strong>
          </div>
        {%endfor%}
    {%endif%}
<div class="board container-fluid mt-3 ">
    <div class="row">
        <div class="col-sm-5 dashboard">
            <h2 style="text-align:center"> Dash board</h2>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <div class="dropdown show">
                          <button class="btn btn-primary dropdown-toggle" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Choose an Opponent  
                        </button>
                        {% if users|length > 1 %}
                          <div class="dropdown-menu pl-2" aria-labelledby="dropdownMenuLink">
                                <form action="{% url 'game_app:play_request' %}" method="post">
                                {% csrf_token %}
                                {% for active_user in users %}
                                {% if active_user != user %}
                                    <div class="form-check pl-4">
                                        <input class="form-check-input" type="radio" value="{{active_user.username}}" id="{{active_user.pk}}" name="selected_user">
                                        <label class="form-check-label" for="{{active_user.pk}}">
                                            {{active_user.username}}
                                        </label>
                                    </div>
                                    {% endif %}
                              {% endfor %}
                                 <button type="submit" class="btn btn-primary">Submit</button>
                                </form>
                          </div>
                        {% else %}
                            <div class="dropdown-menu pl-2" aria-labelledby="dropdownMenuLink">
                                <h4> There are no online Players. </h4>
                            </div>
                        {% endif %}
                    </div>
                </li>
                <li>
                    <h3> Click Play to continue a session </h3>
                    <a href="{% url 'game_app:game_session' %}" class="btn btn-primary btn-lg active btn-sm" role="button" aria-pressed="true">Play</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <div class="col-sm-6">
            {%if user.is_authenticated %}
            <div class="invisible" id="requestBox">
                <h2> You are recieving a request from <span id="sender"> </span></h2>
                <h2> Do You want to confirm?</h2>
                <form action="{% url 'game_app:handle_requests' %}" method="post">
                    {% csrf_token %}
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="option" id="inlineRadio1" >
                        <label class="form-check-label" for="inlineRadio1"> Yes </label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="option" id="inlineRadio2" value="no">
                        <label class="form-check-label" for="inlineRadio2"> No </label>
                    </div>
                    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                </form>
            </div>
            {% endif %}
        </div>
    </div>
</div>

<script src="{% static 'game_app/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'game_app/js/recieve.js' %}"></script>
</body>
</html>
{% endblock %}

game_app/templates/game_app/waiting.html
{% extends "game_app/base.html" %}
{% load static %}
{% block body %}
<html>
<head>
    <title>

    </title>
    <link rel="stylesheet" href="{% static 'game_app/css/style.css' %}">
</head>
<body>
<h1 style="text-align:center">Please wait while your request is sent </h1>
{%if user.is_authenticated %}
<h2 class="invisible" id="rejected" style="text-align:center"> Your request has been rejected navigate to the home page <a href="{% url 'game_app:home' %}">Home</a> </h2>
<div class="container invisible d-flex justify-content-center" id="sent">
    <h2> Your request has been accepted  </h2>
    <form action="{% url 'game_app:game_session' %}" method="get">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary"> Play</button>
    </form>
</div>
{% endif %}
<script src="{% static 'game_app/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'game_app/js/requests.js' %}"></script>
</body>
</html>
{% endblock %}